return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  lazy = false,
  opts = {
    ensure_installed = {
      "asm",
      "bash",
      "c",
      "cmake",
      "cpp",
      "dart",
      "go",
      "haskell",
      "html",
      "http",
      "java",
      "javascript",
      "latex",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "meson",
      "ninja",
      "nix",
      "ocaml",
      "purescript",
      "python",
      "regex",
      "rust",
      "typescript",
      "typst",
      "zig",
    },
    sync_install = true,
    auto_install = true,
    highlight = {
      enable = true,
    },
  },
  config = function(_, opts)
    require("nvim-treesitter.configs").setup(opts)
  end,
}
